# Generated by Django 2.2.3 on 2022-12-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
